export const CSSprocessors = [
  { label: "SCSS", value: "scss", processorId: "1" },
  { label: "cssnext", value: "cssnext", processorId: "2" },
  { label: "CSS-Crush", value: "csscrush", processorId: "3" },
  { label: "CSS-On-Diet", value: "cssondiet", processorId: "4" },
  { label: "Garden (Clojure)", value: "garden", processorId: "5" },
  { label: "Less", value: "less", processorId: "6" },
  { label: "Pleeease", value: "pleeease", processorId: "7" },
  { label: "PostCSS", value: "postcss", processorId: "8" },
  { label: "Rework", value: "rework", processorId: "9" },
  { label: "SASS", value: "sass", processorId: "10" },
  { label: "Sly", value: "sly", processorId: "11" },
  { label: "styled-components", value: "styledcomponents", processorId: "12" },
  { label: "Stylecow", value: "stylecow", processorId: "13" },
  { label: "Stylus", value: "stylus", processorId: "14" },
  { label: "TailwindCSS", value: "tailwindcss", processorId: "15" },
];
