export const JavascriptFrameworks = [
  { label: "Alpine.js", value: "alpinejs", frameworkId: "1" },
  { label: "Angular", value: "angular", frameworkId: "2" },
  { label: "Astro", value: "astro", frameworkId: "3" },
  { label: "Babylon.js", value: "babylonjs", frameworkId: "4" },
  { label: "Blitz.js", value: "blitzjs", frameworkId: "5" },
  { label: "Brunch", value: "brunch", frameworkId: "6" },
  { label: "Cylon.js", value: "clyonjs", frameworkId: "7" },
  { label: "Docusaurus 1", value: "docusaurus1", frameworkId: "8" },
  { label: "Docusaurus 2", value: "docusaurus2", frameworkId: "9" },
  { label: "Dojo", value: "dojo", frameworkId: "10" },
  { label: "Eleventy", value: "eleventy", frameworkId: "11" },
  { label: "Ember.js", value: "emberjs", frameworkId: "12" },
  { label: "Gatsby.js", value: "gatsbyjs", frameworkId: "13" },
  { label: "Gridsome", value: "gridsome", frameworkId: "14" },
  { label: "Hexo", value: "hexo", frameworkId: "15" },
  { label: "Hugo", value: "hugo", frameworkId: "16" },
  { label: "Hydrogen", value: "hydrogen", frameworkId: "17" },
  { label: "Ionic Angular", value: "ionicangular", frameworkId: "18" },
  { label: "Ionic React", value: "ionicreact", frameworkId: "19" },
  { label: "Jekyll", value: "Jekyll", frameworkId: "20" },
  { label: "Middleman", value: "middleman", frameworkId: "21" },
  { label: "Next.js", value: "nextjs", frameworkId: "22" },
  { label: "Nightwatch.js", value: "nextjs", frameworkId: "23" },
  { label: "Nuxt.js", value: "nuxtjs", frameworkId: "24" },
  { label: "Parcel", value: "parcel", frameworkId: "25" },
  { label: "Polymer", value: "polymer", frameworkId: "26" },
  { label: "Preact", value: "preact", frameworkId: "27" },
  { label: "React.js", value: "reactjs", frameworkId: "28" },
  { label: "React Native", value: "reactnative", frameworkId: "29" },
  { label: "Redwood JS", value: "redwoodjs", frameworkId: "30" },
  { label: "Remix", value: "remix", frameworkId: "31" },
  { label: "Saber", value: "saber", frameworkId: "32" },
  { label: "Sapper", value: "sapper", frameworkId: "33" },
  { label: "Scully", value: "scully", frameworkId: "34" },
  { label: "Solid JS", value: "solidjs", frameworkId: "35" },
  { label: "Sanity", value: "sanity", frameworkId: "35" },
  { label: "Stencil", value: "stencil", frameworkId: "37" },
  { label: "Svelte", value: "svelte", frameworkId: "38" },
  { label: "SvelteKit", value: "sveltekit", frameworkId: "39" },
  { label: "UmiJS", value: "umijs", frameworkId: "40" },
  { label: "Vite", value: "vite", frameworkId: "41" },
  { label: "Vue.js", value: "vuejs", frameworkId: "42" },
  { label: "Zola", value: "zola", frameworkId: "43" },
  { label: "Other", value: "other", frameworkId: "44" },
];
