export const JavascriptFrameworks = [
  // { label: "Alpine.js", value: "alpinejs", frameworkId: "1", syntaxHighlight: "jsx" },
  // { label: "Angular", value: "angular", frameworkId: "2", syntaxHighlight: "jsx" },
  { label: "Astro", value: "astro", frameworkId: "3", syntaxHighlight: "jsx" },
/*   { label: "Babylon.js", value: "babylonjs", frameworkId: "4", syntaxHighlight: "jsx" }, */ //LIBRARY
  // { label: "Blitz.js", value: "blitzjs", frameworkId: "5", syntaxHighlight: "jsx" },
  { label: "Brunch", value: "brunch", frameworkId: "6", syntaxHighlight: "jsx" },
  { label: "Cylon.js", value: "clyonjs", frameworkId: "7", syntaxHighlight: "jsx" },
  { label: "Docusaurus 1", value: "docusaurus1", frameworkId: "8", syntaxHighlight: "jsx" },
  { label: "Docusaurus 2", value: "docusaurus2", frameworkId: "9", syntaxHighlight: "jsx" },
  { label: "Dojo", value: "dojo", frameworkId: "10", syntaxHighlight: "jsx" },
  { label: "Eleventy", value: "eleventy", frameworkId: "11", syntaxHighlight: "jsx" },
  { label: "Ember.js", value: "emberjs", frameworkId: "12", syntaxHighlight: "jsx" },
  { label: "Gatsby.js", value: "gatsbyjs", frameworkId: "13", syntaxHighlight: "jsx" },
  { label: "Gridsome", value: "gridsome", frameworkId: "14", syntaxHighlight: "jsx" },
  { label: "Hexo", value: "hexo", frameworkId: "15", syntaxHighlight: "jsx" },
  { label: "Hugo", value: "hugo", frameworkId: "16", syntaxHighlight: "jsx" },
  { label: "Hydrogen", value: "hydrogen", frameworkId: "17", syntaxHighlight: "jsx" },
  { label: "Ionic Angular", value: "ionicangular", frameworkId: "18", syntaxHighlight: "jsx" },
  { label: "Ionic React", value: "ionicreact", frameworkId: "19", syntaxHighlight: "jsx" },
  { label: "Jekyll", value: "Jekyll", frameworkId: "20", syntaxHighlight: "jsx" },
  { label: "Middleman", value: "middleman", frameworkId: "21", syntaxHighlight: "jsx" },
  { label: "Next.js", value: "nextjs", frameworkId: "22", syntaxHighlight: "jsx" },
  { label: "Nightwatch.js", value: "nextjs", frameworkId: "23", syntaxHighlight: "jsx" },
  { label: "Nuxt.js", value: "nuxtjs", frameworkId: "24", syntaxHighlight: "jsx" },
  { label: "Parcel", value: "parcel", frameworkId: "25", syntaxHighlight: "jsx" },
  { label: "Polymer", value: "polymer", frameworkId: "26", syntaxHighlight: "jsx" },
  { label: "Preact", value: "preact", frameworkId: "27", syntaxHighlight: "jsx" },
  { label: "React.js", value: "reactjs", frameworkId: "28", syntaxHighlight: "jsx" },
  { label: "React Native", value: "reactnative", frameworkId: "29", syntaxHighlight: "jsx" },
  { label: "Redwood JS", value: "redwoodjs", frameworkId: "30", syntaxHighlight: "jsx" },
  { label: "Remix", value: "remix", frameworkId: "31", syntaxHighlight: "jsx" },
  { label: "Saber", value: "saber", frameworkId: "32", syntaxHighlight: "jsx" },
  { label: "Sapper", value: "sapper", frameworkId: "33", syntaxHighlight: "jsx" },
  { label: "Scully", value: "scully", frameworkId: "34", syntaxHighlight: "jsx" },
  { label: "Solid JS", value: "solidjs", frameworkId: "35", syntaxHighlight: "jsx" },
  { label: "Sanity", value: "sanity", frameworkId: "35", syntaxHighlight: "jsx" },
  { label: "Stencil", value: "stencil", frameworkId: "37", syntaxHighlight: "jsx" },
  { label: "Svelte", value: "svelte", frameworkId: "38", syntaxHighlight: "jsx" },
  { label: "SvelteKit", value: "sveltekit", frameworkId: "39", syntaxHighlight: "jsx" },
  { label: "UmiJS", value: "umijs", frameworkId: "40", syntaxHighlight: "jsx" },
  { label: "Vite", value: "vite", frameworkId: "41", syntaxHighlight: "jsx" },
  { label: "Vue.js", value: "vuejs", frameworkId: "42", syntaxHighlight: "jsx" },
  { label: "Zola", value: "zola", frameworkId: "43", syntaxHighlight: "jsx" },
  { label: "Other", value: "other", frameworkId: "44", syntaxHighlight: "jsx" },
];
