export const JavascriptFrameworks = [
  { label: "Alpine.js", value: "alpinejs", langId: "1" },
  { label: "Angular", value: "angular", langId: "2" },
  { label: "Astro", value: "astro", langId: "3" },
  { label: "Babylon.js", value: "babylonjs", langId: "4" },
  { label: "Blitz.js", value: "blitzjs", langId: "5" },
  { label: "Brunch", value: "brunch", langId: "6" },
  { label: "Cylon.js", value: "clyonjs", langId: "7" },
  { label: "Docusaurus 1", value: "docusaurus1", langId: "8" },
  { label: "Docusaurus 2", value: "docusaurus2", langId: "9" },
  { label: "Dojo", value: "dojo", langId: "10" },
  { label: "Eleventy", value: "eleventy", langId: "11" },
  { label: "Ember.js", value: "emberjs", langId: "12" },
  { label: "Gatsby.js", value: "gatsbyjs", langId: "13" },
  { label: "Gridsome", value: "gridsome", langId: "14" },
  { label: "Hexo", value: "hexo", langId: "15" },
  { label: "Hugo", value: "hugo", langId: "16" },
  { label: "Hydrogen", value: "hydrogen", langId: "17" },
  { label: "Ionic Angular", value: "ionicangular", langId: "18" },
  { label: "Ionic React", value: "ionicreact", langId: "19" },
  { label: "Jekyll", value: "Jekyll", langId: "20" },
  { label: "Middleman", value: "middleman", langId: "21" },
  { label: "Next.js", value: "nextjs", langId: "22" },
  { label: "Nightwatch.js", value: "nextjs", langId: "23" },
  { label: "Nuxt.js", value: "nuxtjs", langId: "24" },
  { label: "Parcel", value: "parcel", langId: "25" },
  { label: "Polymer", value: "polymer", langId: "26" },
  { label: "Preact", value: "preact", langId: "27" },
  { label: "React.js", value: "reactjs", langId: "28" },
  { label: "React Native", value: "reactnative", langId: "29" },
  { label: "Redwood JS", value: "redwoodjs", langId: "30" },
  { label: "Remix", value: "remix", langId: "31" },
  { label: "Saber", value: "saber", langId: "32" },
  { label: "Sapper", value: "sapper", langId: "33" },
  { label: "Scully", value: "scully", langId: "34" },
  { label: "Solid JS", value: "solidjs", langId: "35" },
  { label: "Sanity", value: "sanity", langId: "35" },
  { label: "Stencil", value: "stencil", langId: "37" },
  { label: "Svelte", value: "svelte", langId: "38" },
  { label: "SvelteKit", value: "sveltekit", langId: "39" },
  { label: "UmiJS", value: "umijs", langId: "40" },
  { label: "Vite", value: "vite", langId: "41" },
  { label: "Vue.js", value: "vuejs", langId: "42" },
  { label: "Zola", value: "zola", langId: "43" },
  { label: "Other", value: "other", langId: "44" },
];
