export const LanguageOptions = [
  { label: "ABAP", value: "abap", langId: "1" },
  { label: "ABC", value: "abc", langId: "2" },
  { label: "ActionScript", value: "actionscript", langId: "3" },
  { label: "ADA", value: "ada", langId: "4" },
  { label: "Apache Conf", value: "apacheconf", langId: "5" },
  { label: "AsciiDoc", value: "asciidoc", langId: "6" },
  { label: "Assembly x86", value: "assemblyx86", langId: "7" },
  { label: "AutoHotKey", value: "autohotKey", langId: "8" },
  { label: "BatchFile", value: "batchfile", langId: "9" },
  { label: "Bro", value: "bro", langId: "10" },
  { label: "C and C", value: "candc", langId: "11" },
  { label: "C9Search", value: "c9search", langId: "12" },
  { label: "Cirru", value: "cirru", langId: "13" },
  { label: "Clojure", value: "clojure", langId: "14" },
  { label: "Cobol", value: "cobol", langId: "15" },
  { label: "CoffeScript", value: "coffescript", langId: "16" },
  { label: "ColdFusion", value: "coldfusion", langId: "17" },
  { label: "C#", value: "csharp", langId: "18" },
  { label: "CSS", value: "css", langId: "19" },
  { label: "Curly", value: "curly", langId: "20" },
  { label: "D", value: "d", langId: "21" },
  { label: "Dart", value: "dart", langId: "22" },
  { label: "Diff", value: "diff", langId: "23" },
  { label: "Django", value: "django", langId: "24" },
  { label: "DockerFile", value: "dockerFile", langId: "25" },
  { label: "Dot", value: "dot", langId: "26" },
  { label: "Drools", value: "drools", langId: "27" },
  { label: "Eiffel", value: "eiffel", langId: "28" },
  { label: "EJS", value: "ejs", langId: "29" },
  { label: "Elixir", value: "elixir", langId: "30" },
  { label: "Elm", value: "elm", langId: "31" },
  { label: "Erlang", value: "erlang", langId: "32" },
  { label: "Forth", value: "forth", langId: "33" },
  { label: "Fortran", value: "fortran", langId: "34" },
  { label: "FreeMarker", value: "freeMarker", langId: "35" },
  { label: "Gcode", value: "gcode", langId: "36" },
  { label: "Gherkin", value: "gherkin", langId: "37" },
  { label: "Gitignore", value: "gitignore", langId: "38" },
  { label: "Glsl", value: "glsl", langId: "39" },
  { label: "Gobstones", value: "gobstones", langId: "40" },
  { label: "Go", value: "go", langId: "41" },
  { label: "GraphQLSchema", value: "graphqlschema", langId: "42" },
  { label: "Groovy", value: "groovy", langId: "43" },
  { label: "HAML", value: "haml", langId: "44" },
  { label: "Handlebars", value: "handlebars", langId: "45" },
  { label: "Haskell", value: "haskell", langId: "46" },
  { label: "Haskell Cabal", value: "haskellcabal", langId: "47" },
  { label: "haXe", value: "haxe", langId: "48" },
  { label: "Hjson", value: "hjson", langId: "49" },
  { label: "HTML", value: "html", langId: "50" },
  { label: "HTML (Elixir)", value: "htmlelixir", langId: "51" },
  { label: "HTML (Ruby)", value: "htmlruby", langId: "52" },
  { label: "Java", value: "java", langId: "53" },
  { label: "JavaScript", value: "javascript", langId: "54" },
  { label: "JSON", value: "json", langId: "55" },
  { label: "JSONiq", value: "jsoniq", langId: "56" },
  { label: "JSP", value: "jsp", langId: "57" },
  { label: "JSSM", value: "jssm", langId: "58" },
  { label: "JSX", value: "jsx", langId: "59" },
  { label: "Julia", value: "julia", langId: "60" },
  { label: "Kotlin", value: "kotlin", langId: "61" },
  { label: "LaTex", value: "latex", langId: "62" },
  { label: "LESS", value: "less", langId: "63" },
  { label: "Lean", value: "lean", langId: "64" },
  { label: "Liquid", value: "liquid", langId: "65" },
  { label: "Lisp", value: "lisp", langId: "66" },
  { label: "LiveScript", value: "livescript", langId: "67" },
  { label: "LogiQL", value: "logiql", langId: "68" },
  { label: "LSL", value: "lsl", langId: "69" },
  { label: "Lua", value: "lua", langId: "70" },
  { label: "LuaPage", value: "luapage", langId: "71" },
  { label: "Lucene", value: "lucene", langId: "72" },
  { label: "Makefile", value: "makefile", langId: "73" },
  { label: "Markdown", value: "markdown", langId: "74" },
  { label: "Mask", value: "mask", langId: "75" },
  { label: "MATLAB", value: "matlab", langId: "76" },
  { label: "Maze", value: "maze", langId: "77" },
  { label: "MEL", value: "mel", langId: "78" },
  { label: "Node.js", value: "nodejs", langId: "137"},
  { label: "MUSHCode", value: "mushcode", langId: "79" },
  { label: "MySQL", value: "mysql", langId: "80" },
  { label: "Nix", value: "nix", langId: "81" },
  { label: "NSIS", value: "nsis", langId: "82" },
  { label: "Objective-C", value: "objectivec", langId: "83" },
  { label: "OCaml", value: "ocaml", langId: "84" },
  { label: "Pascal", value: "pascal", langId: "85" },
  { label: "Perl", value: "perl", langId: "86" },
  { label: "pgSQL", value: "pgsql", langId: "87" },
  { label: "PHP", value: "php", langId: "88" },
  { label: "Pig", value: "pig", langId: "89" },
  { label: "Powershell", value: "powershell", langId: "90" },
  { label: "Praat", value: "praat", langId: "91" },
  { label: "Prolog", value: "prolog", langId: "92" },
  { label: "Properties", value: "properties", langId: "93" },
  { label: "Protobuf", value: "protobuf", langId: "94" },
  { label: "Python", value: "python", langId: "95" },
  { label: "R", value: "r", langId: "96" },
  { label: "Razor", value: "razor", langId: "97" },
  { label: "RDoc", value: "rdoc", langId: "98" },
  { label: "RHTML", value: "rhtml", langId: "99" },
  { label: "RST", value: "rst", langId: "100" },
  { label: "Ruby", value: "ruby", langId: "101" },
  { label: "Rust", value: "rust", langId: "102" },
/*   { label: "SASS", value: "sass", langId: "103" }, */
  { label: "SCAD", value: "scad", langId: "104" },
  { label: "Scala", value: "scala", langId: "105" },
  { label: "Scheme", value: "scheme", langId: "106" },
/*   { label: "SCSS", value: "scss", langId: "107" }, */
  { label: "SH", value: "sh", langId: "108" },
  { label: "SJS", value: "sjs", langId: "109" },
  { label: "Smarty", value: "smarty", langId: "110" },
  { label: "snippets", value: "snippets", langId: "111" },
  { label: "Soy Template", value: "soytemplate", langId: "112" },
  { label: "Space", value: "space", langId: "113" },
  { label: "SQL", value: "sql", langId: "114" },
  { label: "SQLServer", value: "sqlserver", langId: "115" },
  { label: "Stylus", value: "stylus", langId: "116" },
  { label: "SVG", value: "svg", langId: "117" },
  { label: "Dart", value: "dart", langId: "118" },
  { label: "Swift", value: "swift", langId: "119" },
  { label: "Tcl", value: "tcl", langId: "120" },
  { label: "Tex", value: "tex", langId: "121" },
  { label: "Text", value: "text", langId: "122" },
  { label: "Textile", value: "Textile", langId: "123" },
  { label: "Toml", value: "toml", langId: "124" },
  { label: "TSX", value: "tsx", langId: "125" },
  { label: "Twig", value: "twig", langId: "126" },
  { label: "Typescript", value: "typescript", langId: "127" },
  { label: "Vala", value: "vala", langId: "128" },
  { label: "VBScript", value: "vbscript", langId: "129" },
  { label: "Velocity", value: "velocity", langId: "130" },
  { label: "Verilog", value: "verilog", langId: "131" },
  { label: "VHDL", value: "vhdl", langId: "132" },
  { label: "Wollok", value: "wollok", langId: "133" },
  { label: "XML", value: "xml", langId: "134" },
  { label: "XQuery", value: "xquery", langId: "135" },
  { label: "YAML", value: "yaml", langId: "136" },
  { label: "Other", value: "other", langId: "138" },
];

/* LAST: Other - 138 */