export const LanguageOptions = [
  { label: "ABAP", value: "abap", langId: "1", fileExtension: "",  syntaxHighlight: "abap", accessory: false },
  { label: "ABC", value: "abc", langId: "2", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "ActionScript", value: "actionscript", langId: "3", fileExtension: "",  syntaxHighlight: "actionscript", accessory: false },
  { label: "AppleScript", value: "applescript", langId: "148", fileExtension: "",  syntaxHighlight: "applescript", accessory: false },
  { label: "ADA", value: "ada", langId: "4", fileExtension: "",  syntaxHighlight: "ada", accessory: false },
  { label: "Arduino", value: "arduino", langId: "140", fileExtension: "",  syntaxHighlight: "arduino", accessory: false },
  { label: "Apache Configuration", value: "apacheconf", langId: "5", fileExtension: "",  syntaxHighlight: "apacheconf", accessory: false },
  { label: "AsciiDoc", value: "asciidoc", langId: "6", fileExtension: "",  syntaxHighlight: "asciidoc", accessory: false },
  { label: "Assembly x86", value: "assemblyx86", langId: "7", fileExtension: "",  syntaxHighlight: "asm6502", accessory: false },
  { label: "AutoHotKey", value: "autohotkey", langId: "8", fileExtension: "",  syntaxHighlight: "autohotkey", accessory: false },
  { label: "Batch File", value: "batchfile", langId: "9", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "Brainfuck", value: "brainfuck", langId: "147", fileExtension: "br",  syntaxHighlight: "brainfuck", accessory: false },
  { label: "Bro", value: "bro", langId: "10", fileExtension: "",  syntaxHighlight: "bro", accessory: false },
  { label: "C", value: "c", langId: "141", fileExtension: "",  syntaxHighlight: "c", accessory: false },
  { label: "C and C", value: "candc", langId: "11", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "C9Search", value: "c9search", langId: "12", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "Cirru", value: "cirru", langId: "13", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "Clojure", value: "clojure", langId: "14", fileExtension: "",  syntaxHighlight: "clojure", accessory: false },
  { label: "Cobol", value: "cobol", langId: "15", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "CoffeScript", value: "coffescript", langId: "16", fileExtension: "",  syntaxHighlight: "coffeescript", accessory: false },
  { label: "ColdFusion", value: "coldfusion", langId: "17", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "CSS", value: "css", langId: "19", fileExtension: "css",  syntaxHighlight: "css", accessory: true },
  { label: "Curly", value: "curly", langId: "20", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "C++", value: "cpp", langId: "142", fileExtension: "",  syntaxHighlight: "cpp", accessory: false },
  { label: "C#", value: "csharp", langId: "18", fileExtension: "",  syntaxHighlight: "csharp", accessory: false },
  { label: "D", value: "d", langId: "21", fileExtension: "",  syntaxHighlight: "d", accessory: false },
  { label: "Dart", value: "dart", langId: "22", fileExtension: "",  syntaxHighlight: "dart", accessory: false },
  { label: "Diff", value: "diff", langId: "23", fileExtension: "",  syntaxHighlight: "diff", accessory: false },
  { label: "Django", value: "django", langId: "24", fileExtension: "",  syntaxHighlight: "django", accessory: false },
  { label: "Docker File", value: "dockerfile", langId: "25", fileExtension: "",  syntaxHighlight: "docker", accessory: false },
  { label: "Dot", value: "dot", langId: "26", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "Drools", value: "drools", langId: "27", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "Eiffel", value: "eiffel", langId: "28", fileExtension: "",  syntaxHighlight: "eiffel", accessory: false },
  { label: "EJS", value: "ejs", langId: "29", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "Elixir", value: "elixir", langId: "30", fileExtension: "",  syntaxHighlight: "elixir", accessory: false },
  { label: "Elm", value: "elm", langId: "31", fileExtension: "",  syntaxHighlight: "elm", accessory: false },
  { label: "Erlang", value: "erlang", langId: "32", fileExtension: "",  syntaxHighlight: "erlang", accessory: false },
  { label: "Forth", value: "forth", langId: "33", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "Fortran", value: "fortran", langId: "34", fileExtension: "",  syntaxHighlight: "fortran", accessory: false },
  { label: "FreeMarker", value: "freeMarker", langId: "35", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "Gcode", value: "gcode", langId: "36", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "Gherkin", value: "gherkin", langId: "37", fileExtension: "",  syntaxHighlight: "gherkin", accessory: false },
  { label: "Git", value: "git", langId: "139", fileExtension: "",  syntaxHighlight: "git", accessory: false },
  { label: "Gitignore", value: "gitignore", langId: "38", fileExtension: "",  syntaxHighlight: "git", accessory: false },
  { label: "Glsl", value: "glsl", langId: "39", fileExtension: "",  syntaxHighlight: "glsl", accessory: false },
  { label: "Gobstones", value: "gobstones", langId: "40", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "Go", value: "go", langId: "41", fileExtension: "",  syntaxHighlight: "go", accessory: false },
  { label: "GraphQL", value: "graphql", langId: "42", fileExtension: "",  syntaxHighlight: "graphql", accessory: false },
  { label: "Groovy", value: "groovy", langId: "43", fileExtension: "",  syntaxHighlight: "groovy", accessory: false },
/*   { label: "HAML", value: "haml", langId: "44", fileExtension: "",  syntaxHighlight: "haml" }, *///Moved to HTMLTemplates
  { label: "Handlebars", value: "handlebars", langId: "45", fileExtension: "",  syntaxHighlight: "handlebars", accessory: false },
  { label: "Haskell", value: "haskell", langId: "46", fileExtension: "",  syntaxHighlight: "haskell", accessory: false },
  { label: "Haskell Cabal", value: "haskellcabal", langId: "47", fileExtension: "",  syntaxHighlight: "haskell", accessory: false },
  { label: "haXe", value: "haxe", langId: "48", fileExtension: "",  syntaxHighlight: "haxe", accessory: false },
  { label: "Hjson", value: "hjson", langId: "49", fileExtension: "",  syntaxHighlight: "json", accessory: false },
  { label: "HTML", value: "html", langId: "50", fileExtension: "html",  syntaxHighlight: "html", accessory: false },
  { label: "HTML (Elixir)", value: "htmlelixir", langId: "51", fileExtension: "",  syntaxHighlight: "html", accessory: false },
  { label: "HTML (Ruby)", value: "htmlruby", langId: "52", fileExtension: "",  syntaxHighlight: "html", accessory: false },
  { label: "HTTP", value: "http", langId: "143", fileExtension: "",  syntaxHighlight: "http", accessory: false },
  { label: "Java", value: "java", langId: "53", fileExtension: "",  syntaxHighlight: "java", accessory: false },
  { label: "JavaScript", value: "javascript", langId: "54", fileExtension: "js",  syntaxHighlight: "javascript", accessory: true },
  { label: "JSON", value: "json", langId: "55", fileExtension: "",  syntaxHighlight: "json", accessory: false },
  { label: "JSONiq", value: "jsoniq", langId: "56", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "JSP", value: "jsp", langId: "57", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "JSSM", value: "jssm", langId: "58", fileExtension: "",  syntaxHighlight: "", accessory: false },
/*   { label: "JSX", value: "jsx", langId: "59", fileExtension: "",  syntaxHighlight: "" }, */  //Moved to Javasript frameworks
  { label: "Julia", value: "julia", langId: "60", fileExtension: "",  syntaxHighlight: "julia", accessory: false },
  { label: "Kotlin", value: "kotlin", langId: "61", fileExtension: "",  syntaxHighlight: "kotlin", accessory: false },
  { label: "LaTex", value: "latex", langId: "62", fileExtension: "",  syntaxHighlight: "latex", accessory: false },
/*   { label: "LESS", value: "less", langId: "63", fileExtension: "",  syntaxHighlight: "less", accessory: false }, */  //Moved to CSS proccessors
  { label: "Lean", value: "lean", langId: "64", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "Liquid", value: "liquid", langId: "65", fileExtension: "",  syntaxHighlight: "liquid", accessory: false },
  { label: "Lisp", value: "lisp", langId: "66", fileExtension: "",  syntaxHighlight: "lisp", accessory: false },
  { label: "LiveScript", value: "livescript", langId: "67", fileExtension: "",  syntaxHighlight: "livescript", accessory: false },
  { label: "LogiQL", value: "logiql", langId: "68", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "LSL", value: "lsl", langId: "69", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "Lua", value: "lua", langId: "70", fileExtension: "",  syntaxHighlight: "lua", accessory: false },
  { label: "Lua Page", value: "luapage", langId: "71", fileExtension: "",  syntaxHighlight: "lua", accessory: false },
  { label: "Lucene", value: "lucene", langId: "72", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "Makefile", value: "makefile", langId: "73", fileExtension: "",  syntaxHighlight: "makefile", accessory: false },
/*   { label: "Markdown", value: "markdown", langId: "74", fileExtension: "",  syntaxHighlight: "markdown" }, */ //Moved to HTMLTemplates
  { label: "Markup", value: "markup", langId: "149", fileExtension: "",  syntaxHighlight: "markup", accessory: false },
  { label: "Mask", value: "mask", langId: "75", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "MATLAB", value: "matlab", langId: "76", fileExtension: "",  syntaxHighlight: "matlab", accessory: false },
  { label: "Maze", value: "maze", langId: "77", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "MEL", value: "mel", langId: "78", fileExtension: "",  syntaxHighlight: "mel", accessory: false },
  { label: "Node.js", value: "nodejs", langId: "137", fileExtension: "",  syntaxHighlight: "javascript", accessory: false },
  { label: "MUSHCode", value: "mushcode", langId: "79", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "MySQL", value: "mysql", langId: "80", fileExtension: "",  syntaxHighlight: "sql", accessory: false },
  { label: "Nix", value: "nix", langId: "81", fileExtension: "",  syntaxHighlight: "nix", accessory: false },
  { label: "NSIS", value: "nsis", langId: "82", fileExtension: "",  syntaxHighlight: "nsis", accessory: false },
  { label: "Objective-C", value: "objectivec", langId: "83", fileExtension: "",  syntaxHighlight: "objectivec", accessory: false },
  { label: "OCaml", value: "ocaml", langId: "84", fileExtension: "",  syntaxHighlight: "ocaml", accessory: false },
  { label: "Pascal", value: "pascal", langId: "85", fileExtension: "",  syntaxHighlight: "pascal", accessory: false },
  { label: "Perl", value: "perl", langId: "86", fileExtension: "",  syntaxHighlight: "perl", accessory: false },
  { label: "pgSQL", value: "pgsql", langId: "87", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "PHP", value: "php", langId: "88", fileExtension: "",  syntaxHighlight: "php", accessory: false },
  { label: "Pig", value: "pig", langId: "89", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "PostgreSQL", value: "postgresql", langId: "144", fileExtension: "",  syntaxHighlight: "sql", accessory: false },
  { label: "Powershell", value: "powershell", langId: "90", fileExtension: "",  syntaxHighlight: "powershell", accessory: false },
  { label: "Praat", value: "praat", langId: "91", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "Prolog", value: "prolog", langId: "92", fileExtension: "",  syntaxHighlight: "prolog", accessory: false },
  { label: "Properties", value: "properties", langId: "93", fileExtension: "",  syntaxHighlight: "properties", accessory: false },
  { label: "Protocol Buffers", value: "protobuf", langId: "94", fileExtension: "",  syntaxHighlight: "protobuf", accessory: false },
  { label: "Python", value: "python", langId: "95", fileExtension: "",  syntaxHighlight: "python", accessory: false },
  { label: "R", value: "r", langId: "96", fileExtension: "",  syntaxHighlight: "r", accessory: false },
  { label: "Razor", value: "razor", langId: "97", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "RDoc", value: "rdoc", langId: "98", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "RHTML", value: "rhtml", langId: "99", fileExtension: "",  syntaxHighlight: "ruby", accessory: false }, //Ruby HTML
  { label: "reST (reStructuredText)", value: "rest", langId: "100", fileExtension: "",  syntaxHighlight: "rest", accessory: false },
  { label: "Ruby", value: "ruby", langId: "101", fileExtension: "",  syntaxHighlight: "ruby", accessory: false },
  { label: "Rust", value: "rust", langId: "102", fileExtension: "",  syntaxHighlight: "rust", accessory: false },
/*   { label: "SASS", value: "sass", langId: "103" },, fileExtension: "",  syntaxHighlight: "" */  //Moved to CSS processors
  { label: "openSCAD", value: "scad", langId: "104", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "Scala", value: "scala", langId: "105", fileExtension: "",  syntaxHighlight: "scala", accessory: false },
  { label: "Scheme", value: "scheme", langId: "106", fileExtension: "",  syntaxHighlight: "scheme", accessory: false },
/*   { label: "SCSS", value: "scss", langId: "107" },, fileExtension: "",  syntaxHighlight: "" */  //Moved to CSS processors
  { label: "Shell script", value: "sh", langId: "108", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "SJS", value: "sjs", langId: "109", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "Smarty", value: "smarty", langId: "110", fileExtension: "",  syntaxHighlight: "", accessory: false },
/*   { label: "snippets", value: "snippets", langId: "111", fileExtension: "",  syntaxHighlight: "", accessory: false }, */ //Unknown
  { label: "Soy (Closure Template)", value: "soy", langId: "112", fileExtension: "",  syntaxHighlight: "soy", accessory: false },
  { label: "Space", value: "space", langId: "113", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "SQL", value: "sql", langId: "114", fileExtension: "",  syntaxHighlight: "sql", accessory: false },
  { label: "SQLServer", value: "sqlserver", langId: "115", fileExtension: "",  syntaxHighlight: "sql", accessory: false },
/*   { label: "Stylus", value: "stylus", langId: "116", fileExtension: "",  syntaxHighlight: "" }, */
  { label: "SVG", value: "svg", langId: "117", fileExtension: "",  syntaxHighlight: "svg", accessory: false },
/*   { label: "Dart", value: "dart", langId: "118", fileExtension: "",  syntaxHighlight: "" }, */  //Repeated line
  { label: "Swift", value: "swift", langId: "119", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "Tcl", value: "tcl", langId: "120", fileExtension: "",  syntaxHighlight: "tcl", accessory: false },
  { label: "Tex", value: "tex", langId: "121", fileExtension: "",  syntaxHighlight: ", accessory: false"},
  { label: "Text", value: "text", langId: "122", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "Textile", value: "textile", langId: "123", fileExtension: "",  syntaxHighlight: "textile", accessory: false },
  { label: "Toml", value: "toml", langId: "124", fileExtension: "",  syntaxHighlight: "", accessory: false },
/*   { label: "TSX", value: "tsx", langId: "125", fileExtension: "",  syntaxHighlight: "" }, */ //Duplicated line > Typescript
/*   { label: "Twig", value: "twig", langId: "126", fileExtension: "",  syntaxHighlight: "twig", accessory: false }, */  //Moved to > HTML templates
  { label: "Typescript", value: "typescript", langId: "127", fileExtension: "",  syntaxHighlight: "typescript", accessory: true },
  { label: "Vala", value: "vala", langId: "128", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "VBScript", value: "vbscript", langId: "129", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "Visual Basic", value: "vb", langId: "146", fileExtension: "",  syntaxHighlight: "visual-basic", accessory: false },
  { label: "Visual Basic .NET", value: "vbnet", langId: "145", fileExtension: "",  syntaxHighlight: "vbnet", accessory: false },
/*   { label: "Velocity", value: "velocity", langId: "130", fileExtension: "",  syntaxHighlight: "velocity", accessory: false }, */  //Moved to > HTML templates
  { label: "Verilog", value: "verilog", langId: "131", fileExtension: "",  syntaxHighlight: "verilog", accessory: false },
  { label: "VHDL", value: "vhdl", langId: "132", fileExtension: "",  syntaxHighlight: "vhdl", accessory: false },
  { label: "Wollok", value: "wollok", langId: "133", fileExtension: "",  syntaxHighlight: "", accessory: false },
  { label: "XML", value: "xml", langId: "134", fileExtension: "",  syntaxHighlight: "", accessory: false },
/*   { label: "XQuery", value: "xquery", langId: "135", fileExtension: "",  syntaxHighlight: "xquery", accessory: false }, */ //Moved to > HTML templates
  { label: "YAML", value: "yaml", langId: "136", fileExtension: "",  syntaxHighlight: "yaml", accessory: false },
  { label: "Other", value: "other", langId: "138", fileExtension: "",  syntaxHighlight: "", accessory: false },

];

/* LAST: Markup - 149 */